#!/usr/bin/env python3
"""decipher-dq: scaffold, verify, extract, bump, hand off, scan.

Six commands. Everything that touches the Decipher server is a human action; the
tool's job is to make the package survive first contact and to phrase the ask.

Exit codes
    0  ok
    1  usage or input error
    2  verification failed (an ERROR finding)
    3  refused: would violate an invariant
"""

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))

from checks import ERROR, WARN, run as run_checks, summarise      # noqa: E402
from checks.common import (config, declaration_hash, parse_fences,  # noqa: E402
                           parse_requires)

CONFIG = config()
COMPANY = CONFIG["test_company"]
HOST = CONFIG["host"]
LOCAL_ROOT = CONFIG["local_root"]
SERVER_ROOT = "%s/%s" % (CONFIG["server_root"].rstrip("/"), COMPANY)
FORBIDDEN = CONFIG["forbidden_companies"]
GENERATED_HEADER = ("<!-- GENERATED by dq.py extract from survey.xml. "
                    "Do not edit. Regenerate instead. -->")
OK, USAGE, FAILED, REFUSED = 0, 1, 2, 3


def die(message, code=USAGE):
    sys.stderr.write("error: %s\n" % message)
    raise SystemExit(code)


def refuse(message):
    sys.stderr.write("refused: %s\n" % message)
    raise SystemExit(REFUSED)


def guard_path(path):
    text = str(Path(path).resolve()).replace("\\", "/")
    named = [c for c in FORBIDDEN if c in text]
    if named or "prod_environment" in text:
        refuse("%s names production (%s). This skill is TEST company %s only."
               % (path, ", ".join(named) or "prod_environment", COMPANY))
    return Path(path).resolve()


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def package_files(package):
    return sorted(p for p in Path(package).rglob("*") if p.is_file())


# --------------------------------------------------------------------------- new

def cmd_new(args):
    archetype_dir = ROOT / "archetypes" / args.archetype
    if not archetype_dir.is_dir():
        available = sorted(p.name for p in (ROOT / "archetypes").iterdir()
                           if p.is_dir())
        die("unknown archetype %r. Available: %s"
            % (args.archetype, ", ".join(available)))

    meta_path = archetype_dir / "archetype.json"
    if not meta_path.is_file():
        die("archetype %r has no archetype.json" % args.archetype)
    archetype = json.loads(meta_path.read_text(encoding="utf-8"))

    if args.questions:
        print("Interview for archetype %r." % args.archetype)
        print("Answer these before scaffolding; the answers become spec.json.\n")
        for i, q in enumerate(archetype.get("questions", []), 1):
            print("%d. %s" % (i, q["ask"]))
            if q.get("why"):
                print("   why it matters: %s" % q["why"])
            if q.get("affects"):
                print("   decides: %s" % ", ".join(q["affects"]))
            print()
        return OK

    if not (archetype_dir / "template").is_dir():
        die("archetype %r has no template in this release (status: %s).\n"
            "Scaffold from 'basic', which is the reference structure every\n"
            "archetype inherits, then apply this archetype's questions and\n"
            "capture shape by hand. Run:\n"
            "    dq.py new --archetype %s --questions\n"
            "to get the interview, and read its spec_template for the shape."
            % (args.archetype, archetype.get("status", "unknown"),
               args.archetype))

    if not args.spec:
        die("--spec is required. Run with --questions first, write spec.json, "
            "then scaffold.")
    spec = json.loads(Path(args.spec).read_text(encoding="utf-8"))
    name = spec.get("name") or args.name
    if not name:
        die("spec.json has no name and --name was not given")
    if not re.fullmatch(r"[a-z][a-z0-9_]{1,62}", name):
        die("DQ name %r must be lowercase snake_case" % name)
    version = int(spec.get("version", 1))

    target = guard_path(args.into) / name / ("v%d" % version)
    if target.exists():
        refuse("%s already exists. A deployed vN is immutable; use dq.py bump."
               % target)

    tokens = {
        "DQ_NAME": name,
        "VERSION": str(version),
        "TITLE": spec.get("title", name.replace("_", " ").title()),
        "OWNER": spec.get("owner", "unknown@example.invalid"),
        "SCOPE": spec.get("scope", "radio"),
        "QUESTION_TAG": spec.get("scope", "radio").split(",")[0].strip(),
        "COMPAT": str(spec.get("compat", "155")),
        "HOST_CLASS": "%s-v%d-host" % (name.replace("_", "-"), version),
        "JS_NAMESPACE": "".join(p.capitalize() for p in name.split("_"))
                        + "V%d" % version,
        "DQ_UPPER": name.upper(),
    }

    if not args.apply:
        print("dry run. Would create %s from archetype %r:" % (target, args.archetype))
        for path in sorted((archetype_dir / "template").rglob("*")):
            if path.is_file():
                print("    %s" % _render_name(
                    path.relative_to(archetype_dir / "template").as_posix(),
                    tokens))
        print("\nRe-run with --apply.")
        return OK

    src = archetype_dir / "template"
    target.mkdir(parents=True)
    for path in sorted(src.rglob("*")):
        if not path.is_file():
            continue
        rel = _render_name(path.relative_to(src).as_posix(), tokens)
        out = target / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        body = path.read_text(encoding="utf-8")
        out.write_text(_render(body, tokens), encoding="utf-8", newline="\n")

    # The spec is rendered too. A spec copied from spec_template still carries
    # tokens in its values -- a capture label of __DQ_UPPER___ORDER, say -- and
    # an unrendered one contradicts the demo it was scaffolded with.
    (target / "spec.json").write_text(
        _render(json.dumps(spec, indent=2), tokens) + "\n",
        encoding="utf-8", newline="\n")

    print("created %s" % target)
    _extract(target, apply=True, quiet=True)
    print("\nNow run: python scripts/dq.py verify %s" % target)
    return OK


def _render(text, tokens):
    for key, value in tokens.items():
        text = text.replace("__%s__" % key, value)
    return text


def _render_name(rel, tokens):
    return _render(rel, tokens)


# ------------------------------------------------------------------------ verify

def cmd_verify(args):
    package = guard_path(args.package)
    if not package.is_dir():
        die("%s is not a directory" % package)
    ctx, findings = run_checks(package, only=set(args.only or []),
                               skip=set(args.skip or []))
    stats = summarise(findings)

    if args.json:
        print(json.dumps({
            "package": str(package),
            "dq": {"name": ctx.name, "version": ctx.version},
            "legacy_demo": ctx.legacy,
            "findings": [f.as_dict() for f in findings],
            **stats,
        }, indent=2))
        return OK if stats["ok"] else FAILED

    errors = [f for f in findings if f.severity == ERROR]
    warnings = [f for f in findings if f.severity == WARN]
    print("verify %s  (%s.%s)" % (package, ctx.name, ctx.version))
    if ctx.legacy:
        print("note: demo has no dq:block fences; fence checks are advisory "
              "for packages authored before the convention.")
    print()
    for finding in errors + warnings:
        print(finding)
        print()
    print("%d error(s), %d warning(s)" % (len(errors), len(warnings)))
    if not errors:
        print("\nPASS -- structural only. This does not execute the DQ and does "
              "not imply server acceptance.")
    return OK if not errors else FAILED


# ----------------------------------------------------------------------- extract

def cmd_extract(args):
    return _extract(guard_path(args.package), apply=args.apply)


def _extract(package, apply=False, quiet=False):
    survey = package / "survey.xml"
    if not survey.is_file():
        die("%s has no survey.xml" % package)
    text = survey.read_text(encoding="utf-8")
    blocks = {b["id"]: b for b in parse_fences(text) if not b.get("unterminated")}
    if not blocks:
        if not quiet:
            print("survey.xml has no dq:block fences; nothing to extract.")
        return OK

    spec = {}
    if (package / "spec.json").is_file():
        spec = json.loads((package / "spec.json").read_text(encoding="utf-8"))

    written = []
    for block_id, filename in (("capture", "capture_block.xml"),
                               ("routing", "routing_block.xml")):
        block = blocks.get(block_id)
        if block is None:
            continue
        body = block["body"].strip("\n")
        digest = declaration_hash(block["body"]) or "unparseable"
        content = "%s\n<!-- capture-hash: %s -->\n%s\n" % (
            GENERATED_HEADER, digest, body)
        written.append((filename, content))

    written.append(("IMPORT.md", _import_md(package, text, blocks, spec)))

    if not apply:
        print("dry run. Would write:")
        for filename, content in written:
            print("    %-20s %d bytes" % (filename, len(content.encode())))
        print("\nRe-run with --apply.")
        return OK

    for filename, content in written:
        (package / filename).write_text(content, encoding="utf-8", newline="\n")
    if not quiet:
        print("wrote %s" % ", ".join(f for f, _ in written))
    else:
        print("generated %s" % ", ".join(f for f, _ in written))
    return OK


def _import_md(package, survey_text, blocks, spec):
    name = spec.get("name", package.parent.name)
    version = spec.get("version", package.name.lstrip("v"))
    lines = []
    add = lines.append

    add("# Using %s.%s" % (name, version))
    add("")
    add("Generated by `dq.py extract`. Do not edit; edit `survey.xml` and "
        "regenerate.")
    add("")
    add("You never need to write HTML, CSS, JavaScript or Python for this "
        "question, and you never need to open a file under `lib/`.")
    add("")

    add("## What to copy, in order")
    add("")
    order = [b for b in parse_fences(survey_text) if not b.get("unterminated")]
    if order:
        add("| # | Block | What to do |")
        add("|---|---|---|")
        for i, block in enumerate(order, 1):
            action = {"edit": "**EDIT THIS**",
                      "copy": "copy as-is",
                      "copy-verbatim": "copy as-is -- **never edit**",
                      "optional": "optional"}.get(block["action"],
                                                  block["action"])
            add("| %d | `%s` -- %s | %s |"
                % (i, block["id"], block["title"] or "", action))
        add("")
        add("Blocks are fenced in `survey.xml` as "
            "`<!-- dq:block id=\"...\" -->` ... `<!-- dq:endblock -->`. Copy "
            "from the opening fence to the closing one.")
        add("")

    if "capture" in blocks:
        add("The question block and the capture block must end up on the "
            "**same page**, in that order, with no `<suspend/>` between them. "
            "A DQ can only write fields that are rendered, so across a page "
            "boundary the screen looks right and the export is empty.")
        add("")
        add("`capture_block.xml` in this package is the same block, generated "
            "from the demo, if you prefer to copy from a file.")
        add("")

    requires = parse_requires(survey_text)
    if requires:
        add("## Survey settings you also need")
        add("")
        add("These are not copy-paste. Set them on your own survey.")
        add("")
        for req in requires:
            if req["kind"] == "survey-attr":
                add("- `<survey>` needs `%s`" % req["rest"])
            elif req["kind"] == "static-asset":
                add("- upload `%s` to your survey's own `static/` folder"
                    % req["rest"])
            else:
                add("- %s %s" % (req["kind"], req["rest"]))
        add("")

    params = spec.get("parameters", [])
    required = [p for p in params if p.get("class") == "public-required"]
    optional = [p for p in params if p.get("class") == "public-optional"]

    if required:
        add("## Settings you must provide")
        add("")
        add("| Setting | What it does |")
        add("|---|---|")
        for entry in required:
            add("| `%s:%s` | %s |" % (name, entry["name"],
                                      entry.get("desc", "")))
        add("")
    if optional:
        add("## Settings you may change")
        add("")
        add("Every one of these has a default that is correct for most studies. "
            "**Leave them out unless you mean to change one.** Restating a "
            "default pins your survey to today's behaviour.")
        add("")
        add("| Setting | Default | What it does |")
        add("|---|---|---|")
        for entry in optional:
            add("| `%s:%s` | `%s` | %s |"
                % (name, entry["name"], entry.get("default", ""),
                   entry.get("desc", "")))
        add("")

    capture = spec.get("capture", [])
    if capture:
        add("## What gets recorded")
        add("")
        add("| Variable | Rows | Holds |")
        add("|---|---|---|")
        for field in capture:
            add("| `%s` | %s | %s |"
                % (field.get("label", ""), field.get("rows", 1) or 1,
                   field.get("desc", "")))
        add("")
        add("Do not rename, reorder or edit these. The question checks them at "
            "startup and refuses to run if they are missing, undersized or "
            "unwritable -- which is deliberate, because the alternative is a "
            "survey that looks fine and records nothing.")
        add("")

    add("## If something looks wrong")
    add("")
    add("Open the survey with a QA link. The question reports exactly what is "
        "misconfigured instead of playing along.")
    add("")
    return "\n".join(lines)


# -------------------------------------------------------------------------- bump

def cmd_bump(args):
    package = guard_path(args.package)
    if not package.is_dir():
        die("%s is not a directory" % package)
    match = re.fullmatch(r"v(\d+)", package.name)
    if not match:
        die("%s is not a vN directory" % package)
    old = int(match.group(1))
    new = int(args.to) if args.to else old + 1
    if new <= old:
        die("--to must be greater than %d" % old)
    target = package.parent / ("v%d" % new)
    if target.exists():
        refuse("%s already exists" % target)

    name = package.parent.name
    plan = []
    for path in package_files(package):
        rel = path.relative_to(package).as_posix()
        new_rel = rel.replace("_v%d" % old, "_v%d" % new)
        plan.append((rel, new_rel))

    title = ""
    meta = package / "meta.xml"
    if meta.is_file():
        found = re.search(r"<title>(.*?)</title>",
                          meta.read_text(encoding="utf-8"), re.S)
        if found:
            title = found.group(1).strip()

    # Anchored rewrites only. An unanchored v<old> -> v<new> replacement
    # corrupts incidental matches; that is why the old tool needed diff review.
    patterns = [
        (re.compile(r"\b%s\.%d\b" % (re.escape(name), old)),
         "%s.%d" % (name, new)),
        (re.compile(r'("version"\s*:\s*)%d\b' % old), r"\g<1>%d" % new),
        (re.compile(r"\b%s v%d\b" % (re.escape(name), old)),
         "%s v%d" % (name, new)),
        (re.compile(r"\b%s_v%d\b" % (re.escape(name), old)),
         "%s_v%d" % (name, new)),
        (re.compile(r"(<version>)\s*%d\s*(</version>)" % old),
         r"\g<1>%d\g<2>" % new),
        (re.compile(r"\b%s-v%d-\b" % (re.escape(name.replace("_", "-")), old)),
         "%s-v%d-" % (name.replace("_", "-"), new)),
        (re.compile(r"\bv%d-host\b" % old), "v%d-host" % new),
        (re.compile(r"\b%sV%d\b" % ("".join(p.capitalize()
                                            for p in name.split("_")), old)),
         "%sV%d" % ("".join(p.capitalize() for p in name.split("_")), new)),
    ]
    if title:
        patterns.append((re.compile(r"\b%s v%d\b" % (re.escape(title), old)),
                         "%s v%d" % (title, new)))

    ambiguous = []
    for path in package_files(package):
        if path.suffix.lower() not in (".xml", ".js", ".css", ".json", ".md",
                                       ".txt"):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in re.finditer(r"\bv%d\b" % old, text):
            window = text[max(0, match.start() - 40):match.end() + 40]
            if any(p.search(window) for p, _ in patterns):
                continue
            line = text.count("\n", 0, match.start()) + 1
            ambiguous.append("%s:%d  %s"
                             % (path.relative_to(package).as_posix(), line,
                                " ".join(window.split())[:70]))

    if not args.apply:
        print("dry run. v%d -> v%d in %s" % (old, new, package.parent))
        print("\nfiles (%d):" % len(plan))
        for rel, new_rel in plan:
            print("    %s%s" % (rel, "  ->  " + new_rel if rel != new_rel else ""))
        if ambiguous:
            print("\nambiguous v%d occurrences NOT rewritten (%d):"
                  % (old, len(ambiguous)))
            for item in ambiguous:
                print("    %s" % item)
            print("\nReview each. bump only rewrites anchored, enumerated sites; "
                  "an unanchored replacement is what corrupted incidental "
                  "matches before.")
        print("\nRe-run with --apply.")
        return OK

    target.mkdir(parents=True)
    for rel, new_rel in plan:
        out = target / new_rel
        out.parent.mkdir(parents=True, exist_ok=True)
        source = package / rel
        if source.suffix.lower() in (".xml", ".js", ".css", ".json", ".md",
                                     ".txt"):
            text = source.read_text(encoding="utf-8")
            for pattern, repl in patterns:
                text = pattern.sub(repl, text)
            out.write_text(text, encoding="utf-8", newline="\n")
        else:
            shutil.copyfile(source, out)
    print("created %s" % target)
    if ambiguous:
        print("\n%d ambiguous v%d occurrence(s) left alone. Review:"
              % (len(ambiguous), old))
        for item in ambiguous:
            print("    %s" % item)
    _extract(target, apply=True, quiet=True)
    print("\nNow run: python scripts/dq.py verify %s" % target)
    return OK


# ----------------------------------------------------------------------- handoff

def cmd_handoff(args):
    template = HANDOFFS.get(args.action)
    if template is None:
        die("unknown action %r. Available: %s"
            % (args.action, ", ".join(sorted(HANDOFFS))))
    print(template(args))
    return OK


def _manifest(package):
    rows, total = [], 0
    for path in package_files(package):
        rel = path.relative_to(package).as_posix()
        size = path.stat().st_size
        total += size
        rows.append("    %-46s %8d  %s" % (rel, size, sha256(path)[:16]))
    return rows, total


def _h_clone(args):
    if not args.source:
        die("--source <survey-id> is required")
    return """ACTION NEEDED (1 of 1)

In Decipher, duplicate survey %s/%s.
Do not edit %s itself.

Download the untouched duplicate to:
    incoming/<new-id>/

Send back: the new numeric survey ID.

Why: /lib/<dq>/vN is not compiled as a survey. A DQ can only run through a
sibling numeric survey that references its version.""" % (COMPANY,
                                                          args.source,
                                                          args.source)


def _h_upload_package(args):
    if not args.package:
        die("--package <dir> is required")
    package = guard_path(args.package)
    match = re.fullmatch(r"v(\d+)", package.name)
    if not match:
        die("%s is not a vN directory" % package)
    name = package.parent.name
    rows, total = _manifest(package)
    return """ACTION NEEDED (%s)

Upload as a whole directory, not file by file:
    local   %s/
    server  %s/lib/%s/%s/

%d files, %d bytes. Checksums below -- compare after upload.
Do not create a lib directory under %s.

Send back: confirmation, or any error text verbatim.

%s""" % (args.step or "1 of 1", package, SERVER_ROOT, name, package.name,
         len(rows), total, "/".join(FORBIDDEN) or "any other company",
         "\n".join(rows))


def _h_upload_survey(args):
    if not args.survey:
        die("--survey <id> is required")
    assets = args.asset or []
    asset_text = "\n".join("    %s" % a for a in assets) or "    none"
    return """ACTION NEEDED (%s)

Upload only this file:
    local   %s/%s/survey.xml
    server  %s/%s/survey.xml

Also upload these static assets the survey needs:
%s

Do not upload uids.bin, original.bin, the pickles, or any log -- those are the
server's, not ours.

Send back: confirmation, or any error text verbatim.""" % (
        args.step or "1 of 1", LOCAL_ROOT, args.survey, SERVER_ROOT,
        args.survey, asset_text)


def _h_compile(args):
    if not args.survey:
        die("--survey <id> is required")
    # Caller-supplied items are ADDED to the standing three, not substituted:
    # the standing three are what catch a package that looks fine.
    look = list(args.look or []) + [
        "radio buttons or text inputs visible anywhere on the page",
        "any configuration-error panel",
        "anything in the browser console",
    ]
    fresh = ("\n    Please use a fresh profile or a private window. A browser "
             "that has\n    already played media on this origin is allowed to "
             "autoplay with sound,\n    so it will hide the very failure this "
             "checks for.\n" if args.media else "")
    return """ACTION NEEDED (%s)

Compile survey %s in Decipher.

If it compiles, open it with a record assigned:
    https://%s/survey/selfserve/%s/%s?list=1

Look for, and tell me about any of these:
%s
%s
Send back: the compiler output verbatim if it failed, or the console text
verbatim if anything appeared there. Not a summary.

Why: the compiler names the exact element and attribute it rejected. A summary
loses the part I need.""" % (
        args.step or "1 of 1", args.survey, HOST, COMPANY, args.survey,
        "\n".join("    - %s" % item for item in look), fresh)


def _h_state(args):
    if not args.survey:
        die("--survey <id> is required")
    return """ACTION NEEDED (%s)

Set survey %s to state="testing".

Why: dev mode does not create respondent records, so there is no exported data
to check against. Data acceptance needs testing state.

Send back: confirmation.""" % (args.step or "1 of 1", args.survey)


def _h_export(args):
    if not args.survey:
        die("--survey <id> is required")
    fixture = "\n".join("    %s" % f for f in (args.fixture or
                                               ["<exact ordered actions>"]))
    return """ACTION NEEDED (%s)

After running the fixture below, export the data for survey %s and send the row
for that respondent.

Fixture:
%s

Send back: the exported row, or the file.

Why: a correct screen does not prove a correct dataset. Hidden inputs can look
right and still be discarded on submit, so the export is the only evidence that
settles it.""" % (args.step or "1 of 1", args.survey, fixture)


HANDOFFS = {
    "clone": _h_clone,
    "upload-package": _h_upload_package,
    "upload-survey": _h_upload_survey,
    "compile": _h_compile,
    "state": _h_state,
    "export": _h_export,
}


# -------------------------------------------------------------------------- scan

def cmd_scan(args):
    root = guard_path(args.root)
    pattern = re.compile(r'uses="%s\.(\d+)"' % re.escape(args.name))
    hits = []
    for path in sorted(root.rglob("survey.xml")):
        text = path.read_text(encoding="utf-8", errors="replace")
        versions = sorted(set(pattern.findall(text)))
        if not versions:
            continue
        rel = path.relative_to(root).as_posix()
        own = "/lib/%s/v" % args.name in "/" + rel
        hits.append({"survey": rel, "versions": versions,
                     "is_own_demo": own})
    if args.json:
        print(json.dumps({"dq": args.name, "references": hits,
                          "count": len([h for h in hits
                                        if not h["is_own_demo"]])}, indent=2))
        return OK
    print("references to %s under %s" % (args.name, root))
    for hit in hits:
        tag = "  (own demo)" if hit["is_own_demo"] else ""
        print("    %-56s %s%s" % (hit["survey"],
                                  ", ".join("v" + v for v in hit["versions"]),
                                  tag))
    adopters = [h for h in hits if not h["is_own_demo"]]
    print("\n%d adopting survey(s) found locally." % len(adopters))
    print("Local only. This cannot see the server, so zero is not proof of "
          "zero adopters.")
    return OK


# -------------------------------------------------------------------------- main

def build_parser():
    parser = argparse.ArgumentParser(
        prog="dq.py", description="Decipher DQ prototyping tools")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("new", help="scaffold a package from an archetype")
    p.add_argument("--archetype", required=True)
    p.add_argument("--spec")
    p.add_argument("--name")
    p.add_argument("--into", default="test_environment/lib")
    p.add_argument("--questions", action="store_true",
                   help="print the archetype's interview and exit")
    p.add_argument("--apply", action="store_true")
    p.set_defaults(func=cmd_new)

    p = sub.add_parser("verify", help="run every local check")
    p.add_argument("package")
    p.add_argument("--only", action="append",
                   help="check or group name; repeatable")
    p.add_argument("--skip", action="append")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=cmd_verify)

    p = sub.add_parser("extract",
                       help="regenerate fragments and IMPORT.md from the demo")
    p.add_argument("package")
    p.add_argument("--apply", action="store_true")
    p.set_defaults(func=cmd_extract)

    p = sub.add_parser("bump", help="fork vN to vN+1")
    p.add_argument("package")
    p.add_argument("--to")
    p.add_argument("--apply", action="store_true")
    p.set_defaults(func=cmd_bump)

    p = sub.add_parser("handoff", help="emit one exact human action")
    p.add_argument("action", choices=sorted(HANDOFFS))
    p.add_argument("--package")
    p.add_argument("--survey")
    p.add_argument("--source")
    p.add_argument("--step", help='e.g. "1 of 2"')
    p.add_argument("--asset", action="append")
    p.add_argument("--look", action="append")
    p.add_argument("--fixture", action="append")
    p.add_argument("--media", action="store_true",
                   help="add the fresh-profile warning for media DQs")
    p.set_defaults(func=cmd_handoff)

    p = sub.add_parser("scan", help="find local surveys using a DQ")
    p.add_argument("--name", required=True)
    p.add_argument("--root", default="test_environment")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=cmd_scan)

    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    try:
        return args.func(args)
    except SystemExit:
        raise
    except FileNotFoundError as exc:
        die(str(exc))
    except json.JSONDecodeError as exc:
        die("invalid JSON: %s" % exc)


if __name__ == "__main__":
    sys.exit(main())
