"""Capture: the contract, the same-page rule, generated-fragment sync."""

import re
from xml.etree import ElementTree

from .common import (error, warn, local, parse_fences,
                     declaration_hash, wrap_fragment)

GENERATED_HEADER = "GENERATED by dq.py extract"


def _capture_block(ctx):
    text = ctx.text.get("survey.xml", "")
    for block in parse_fences(text):
        if block.get("id") == "capture":
            return block
    return None


def _declared_in(body):
    """label -> {type, rows, size} for questions declared in a fragment."""
    out = {}
    try:
        root = ElementTree.fromstring(wrap_fragment(body))
    except ElementTree.ParseError:
        return out
    for node in root.iter():
        tag = local(node.tag)
        if tag not in ("text", "number", "radio", "checkbox", "select"):
            continue
        label = node.get("label")
        if not label:
            continue
        rows = [r.get("label") for r in node
                if local(r.tag) in ("row", "choice")]
        out[label] = {"type": tag, "rows": rows, "size": node.get("size")}
    return out


def capture_contract(ctx):
    """spec.json, the demo declarations, and the adapter probe list must agree."""
    out = []
    if ctx.spec is None:
        return out
    fields = ctx.spec.get("capture", [])
    block = _capture_block(ctx)
    if not fields:
        if block is not None:
            out.append(warn("capture_contract",
                            "the demo has a capture block but spec.json declares "
                            "no capture fields"))
        return out
    if block is None:
        out.append(error("capture_contract",
                         'spec.json declares %d capture field(s) but the demo has '
                         'no dq:block id="capture"' % len(fields),
                         "A DQ cannot declare survey variables. Without a paste "
                         "block the adopting survey has nowhere to record."))
        return out

    declared = _declared_in(block["body"])
    probe_names = set()
    has_roundtrip = False
    for text in ctx.js_files().values():
        for match in re.finditer(
                r"(?:PER_VIDEO_CAPTURE|SINGLE_CAPTURE|EVENT_CAPTURE|"
                r"CAPTURE_FIELDS|PROBE_FIELDS)\s*=\s*\[(.*?)\]", text, re.S):
            probe_names |= set(re.findall(r'"([A-Za-z0-9_]+)"', match.group(1)))
        # A write-then-read-back probe is the handshake, however it is spelled.
        if re.search(r"\.val\(\s*['\"][^'\"]+['\"]\s*\)[\s\S]{0,200}?\.val\(\s*\)",
                     text) or re.search(r"verifyCapture|captureInputs", text):
            has_roundtrip = True

    for field in fields:
        label = field.get("label", "")
        kind = field.get("type", "")
        want_rows = field.get("rows", 0)
        found = declared.get(label)
        if not found:
            out.append(error("capture_contract",
                             "spec.json declares capture field %r but the demo's "
                             "capture block does not" % label,
                             "The variable will not exist on the page and the "
                             "data is discarded on submit."))
            continue
        if kind and found["type"] != kind:
            out.append(error("capture_contract",
                             "capture field %r is %s in spec.json and <%s> in the "
                             "demo" % (label, kind, found["type"])))
        if want_rows and len(found["rows"]) != want_rows:
            out.append(error("capture_contract",
                             "capture field %r wants %d rows, the demo declares %d"
                             % (label, want_rows, len(found["rows"]))))
        if found["type"] == "number":
            out.append(warn("capture_number_type",
                            "capture field %r is <number>" % label,
                            "input type=number silently discards a non-numeric "
                            "write, so a text sentinel probe misreports it. Prefer "
                            "text unless the value is strictly numeric."))
        form = field.get("row_label_form")
        if want_rows and not form:
            out.append(warn("capture_contract",
                            "capture field %r declares no row_label_form" % label,
                            "Row-label padding is not consistent; record it "
                            "rather than assuming it."))
        elif form and found["rows"]:
            first = found["rows"][0]
            if form == "padded" and not re.fullmatch(r"[a-z]+0\d+", first):
                out.append(error("capture_contract",
                                 "capture field %r declares padded row labels but "
                                 "the demo's first row is %r" % (label, first)))
            if form == "plain" and not re.fullmatch(r"[a-z]+[1-9]\d*", first):
                out.append(error("capture_contract",
                                 "capture field %r declares plain row labels but "
                                 "the demo's first row is %r" % (label, first)))

    if probe_names:
        for field in fields:
            label = field.get("label", "")
            key = field.get("param")
            if key and key not in probe_names:
                out.append(error("capture_contract",
                                 "capture field %r (param %s) is not in the "
                                 "adapter's probe list" % (label, key),
                                 "A field absent from the probe list is never "
                                 "verified at startup and can fail silently."))
    elif not has_roundtrip:
        out.append(error("capture_contract",
                         "no startup capture handshake found in the JavaScript",
                         "Without a write-then-read-back probe, a missing or "
                         "unwritable variable is indistinguishable from a "
                         "respondent who did not answer -- and the data is gone."))
    return out


def capture_same_page(ctx):
    """No page boundary between the DQ question and the fields it writes."""
    out = []
    text = ctx.text.get("survey.xml")
    if not text or ctx.name is None:
        return out
    block = _capture_block(ctx)
    if block is None:
        return out
    question = text.find('uses="%s.' % ctx.name)
    if question == -1:
        return out
    between = text[question:block["start"]]
    if re.search(r"<suspend\b", between):
        out.append(error("capture_same_page",
                         "a <suspend/> sits between the DQ question and the "
                         "capture block",
                         "An adapter can only write rendered inputs. Across a "
                         "page boundary the export is empty while the UI looks "
                         "correct."))
    if block["start"] < question:
        out.append(warn("capture_same_page",
                        "the capture block precedes the DQ question",
                        "Legal, but the documented order is question then "
                        "capture; keep IMPORT.md and the demo consistent."))
    return out


def generated_sync(ctx):
    """A generated fragment must still match the demo region it came from."""
    out = []
    text = ctx.text.get("survey.xml", "")
    blocks = {b["id"]: b for b in parse_fences(text) if not b.get("unterminated")}

    pairs = [("capture", "capture_block.xml"), ("routing", "routing_block.xml")]
    for block_id, filename in pairs:
        present = filename in ctx.text
        block = blocks.get(block_id)
        if block is None:
            if present:
                out.append(error("generated_sync",
                                 "%s exists but the demo has no dq:block id=%r"
                                 % (filename, block_id),
                                 "Nothing regenerates it, so it will drift."))
            continue
        if not present:
            out.append(error("generated_sync",
                             "the demo declares a %r block but %s has not been "
                             "generated" % (block_id, filename),
                             "Run dq.py extract."))
            continue
        body = ctx.text[filename]
        if GENERATED_HEADER not in body:
            out.append(error("generated_sync",
                             "%s has no generated header" % filename,
                             "Hand-maintained duplicates drift. Two copies here "
                             "already differ in whitespace, which made diff "
                             "useless as a detector."))
        want = declaration_hash(block["body"])
        got = declaration_hash(re.sub(r"^\s*<!--.*?-->", "", body, count=1,
                                      flags=re.S))
        if want is None or got is None:
            out.append(error("generated_sync",
                             "could not parse %s or its source region" % filename))
        elif want != got:
            out.append(error("generated_sync",
                             "%s no longer matches the demo region it came from "
                             "(%s vs %s)" % (filename, got, want),
                             "Regenerate with dq.py extract; never hand-edit a "
                             "generated fragment."))
    return out


def capture_hash_recorded(ctx):
    """The generated fragment records a hash of its own declarations.

    This is a BUILD-time guarantee, not a runtime one, and the distinction
    matters. At runtime the startup handshake verifies structure -- labels, row
    counts, writability -- which is what actually catches a stale block: if a
    version changed the declarations, the shape differs and the handshake says
    so. The hash exists so that capture_block.xml and the demo region cannot
    silently diverge on disk.

    It replaces a hand-typed capture_block_version, which lived in four sites in
    the previous convention and had three of them still wrong after a rename.
    """
    out = []
    block = _capture_block(ctx)
    if block is None:
        return out
    digest = declaration_hash(block["body"])
    if digest is None:
        out.append(error("capture_hash", "the capture block is not parseable XML"))
        return out
    body = ctx.text.get("capture_block.xml")
    if body is None:
        return out
    found = re.search(r"capture-hash:\s*([0-9a-f]{8,})", body)
    if not found:
        out.append(error("capture_hash",
                         "capture_block.xml records no capture-hash; expected %s"
                         % digest,
                         "Run dq.py extract. Without it nothing detects the two "
                         "copies diverging."))
    elif found.group(1) != digest:
        out.append(error("capture_hash",
                         "capture_block.xml records hash %s but its source region "
                         "hashes to %s" % (found.group(1), digest),
                         "Regenerate with dq.py extract."))
    return out


CHECKS = [capture_contract, capture_same_page, generated_sync,
          capture_hash_recorded]
